export const packs = [
    {
      id: 'Megapack-SST',
      nombre: 'Megapack SST',
      descripcion: 'En el Pack SG-SST te facilitamos con toda la documentación para que puedas implementar un Sistema de Gestión de Seguridad y Salud en el Trabajo desde cero, te brindamos formatos, registros, planes, procedimientos, matrices y dashboard completamentamente editables que se encuentran en formatos word y excel, aplicables para diferentes rubros económicos. Los documentos se encuentran almacenados en la nube, google drive, se te compartira a tu correo gmail para que posteriormente puedas descargarlo.',
      precio: 25,
      antes: 60,
      imagenInicio: '/images/IMG.SST.png',
      imagenDetalle: 'https://res.cloudinary.com/dxq8vo5w2/image/upload/v1728233188/jgainmhlss2ypzy57doq.jpg',
      url: 'https://sstacademype.com/products/formatos-editables-sig',
      estudiantes: '122',
      puntuacion: 4.6,
    },
    {
      id: 'Megapack-SIG',
      nombre: 'Megapack SIG',
      descripcion: 'En el Pack trinorma ISO te facilitamos con toda la documentación para que puedas implementar correctamente las normas ISO 9001, ISO 45001 y la ISO 14001 te brindamos los formatos que aplican en cada uno de las etapas según la estructura del anexo SL de las normas, los formatos son completamentamente editables que se encuentran en formatos word y excel. Los documentos se encuentran almacenados en la nube, google drive, se te compartirá a tu correo gmail para que posteriormente puedas descargarlo.',
      precio: 25,
      antes: 65,
      imagenInicio: '/images/IMG.ISO.png',
      imagenDetalle: 'https://res.cloudinary.com/dxq8vo5w2/image/upload/v1728233187/pmm6uespiwmnripkk73w.jpg',
      url: 'https://sstacademype.com/products/7000-formatos-editables-de-ssoma',
      estudiantes: '85',
      puntuacion: 4.7,
    },
    {
      id: 'Megapack-libro-de-ingles',
      nombre: 'Megapack libro de inglés',
      descripcion: 'Si estás en el proceso de aprender un nuevo idioma y deseas aprender de forma autodidácta o complementar tus conocimientos, te proporcionamos los libros de las principales instituciones, todos los libros de los niveles básico, intermedio y avanzado, asimismo cuentos y audios para reforzar lo aprendido. Los libros se encuentran almacenados en la nube, google drive, se te compartirá a tu correo gmail para que posteriormente puedas descargarlo.',
      precio: 20,
      antes: 30,
      imagenInicio: '/images/IMG.ISO.png',
      imagenDetalle: 'https://res.cloudinary.com/dxq8vo5w2/image/upload/v1728233188/ifc491wrdejlpqvcio6n.jpg',
      url: 'https://sstacademype.com/products/formatos-editables-sig',
      estudiantes: '85',
      puntuacion: 4.5,
    }
  ]